

CREATE DATABASE QuanLyBenhNhan
GO

USE QuanLyBenhNhan
GO

CREATE TABLE KHOA
(
MAKHOA int identity PRIMARY KEY,
TENKHOA nvarchar(40) NOT NULL
)
GO

CREATE TABLE ACCOUNT
(
USERNAME nvarchar(40) PRIMARY KEY,
TEN nvarchar(40) not null,
CHUCVU nvarchar(40) default N' ',
MAKHOA int references KHOA(MAKHOA),
MATKHAU nvarchar(100) not null default 1,
type int not null default 0
)
GO

CREATE TABLE BENHNHAN
(
MABENHNHAN int identity PRIMARY KEY,
HOTEN nvarchar(40) NOT NULL,
GIOITINH nvarchar(4) NOT NULL,
NGHENGHIEP nvarchar(40) NOT NULL,
NGAYSINH date NOT NULL,
DIACHI nvarchar(40) NOT NULL,
SDT nvarchar(12) NOT NULL
)
GO

CREATE TABLE LANKHAM
(
MALANKHAM int identity PRIMARY KEY,
MABENHNHAN  int REFERENCES BENHNHAN(MABENHNHAN),
MAKHOA int REFERENCES KHOA(MAKHOA),
NGAYKHAM date NOT NULL,
TINHTRANG nvarchar(20) default N'Chưa khám'
)
GO

CREATE TABLE LOAIPHONG
(
MALOAIPHONG  int identity PRIMARY KEY,
TENLOAIPHONG nvarchar(40) NOT NULL,
DONGIA money NOT NULL
)
GO

CREATE TABLE PHONG
(
MAPHONG int identity PRIMARY KEY,
SOGIUONG int NOT NULL,
SOBENHNHAN int default 0,
MALOAIPHONG int REFERENCES LOAIPHONG(MALOAIPHONG)
)
GO

CREATE TABLE KETQUA
(
MAKETQUA int identity PRIMARY KEY,
MALANKHAM int REFERENCES LANKHAM(MALANKHAM),
KETQUA nvarchar(200) not null,
)
GO

CREATE TABLE NHAPVIEN	
(
MANHAPVIEN int identity PRIMARY KEY,
MAKETQUA int REFERENCES KETQUA(MAKETQUA),
NGAYNHAP date NOT NULL,
NGAYXUAT date,
TINHTRANG nvarchar(20) default N'Chưa nhập'
)
GO

CREATE TABLE CHITIETNHAPVIEN -- y tá là người cho bệnh nhân vào phòng
(
MACHITIETNHAPVIEN int identity PRIMARY KEY,
MANHAPVIEN int REFERENCES NHAPVIEN(MANHAPVIEN),
MAPHONG int REFERENCES PHONG(MAPHONG) 
)
GO

CREATE TABLE TOATHUOC
(
MATOATHUOC int identity PRIMARY KEY,
MAKETQUA int REFERENCES KETQUA(MAKETQUA),
SONGAY int not null
)
GO

CREATE TABLE THUOC
(
MATHUOC int identity PRIMARY KEY,
TENTHUOC nvarchar(40) NOT NULL,
DONGIA money NOT NULL,
SOLUONG int NOT NULL
)
GO

CREATE TABLE CTTT
(
MACTTT int identity PRIMARY KEY,
MATOATHUOC int REFERENCES TOATHUOC(MATOATHUOC),
SOVIEN int NOT NULL,
MATHUOC int REFERENCES THUOC(MATHUOC)
)
GO

insert into THUOC( TENTHUOC, DONGIA, SOLUONG) values ( 
		N'thuoc A',
		1000,1000)
insert into THUOC( TENTHUOC, DONGIA,  SOLUONG) values ( 
		N'thuoc B',
		1000,1000	)
insert into THUOC( TENTHUOC, DONGIA,  SOLUONG) values ( 
		N'thuoc C',
		1000,1000	)
insert into THUOC( TENTHUOC, DONGIA,  SOLUONG) values ( 
		N'thuoc D',
		2000,1000	)
insert into THUOC( TENTHUOC, DONGIA,  SOLUONG) values ( 
		N'thuoc E',
		2000,2000	)

insert into LOAIPHONG( TENLOAIPHONG, DONGIA) values ( 
		N'Binh thuong ',
		2000)
insert into LOAIPHONG(TENLOAIPHONG, DONGIA) values ( 
		N'Cao cap',
		3000)
insert into LOAIPHONG( TENLOAIPHONG, DONGIA) values ( 
		N'VIP',
		5000)

insert into PHONG( SOGIUONG, MALOAIPHONG) values (  4, 1)
insert into PHONG( SOGIUONG, MALOAIPHONG) values (  4, 2)
insert into PHONG( SOGIUONG, MALOAIPHONG) values (  4, 3)

insert into KHOA( TENKHOA) values (
		N'Khám bệnh')
insert into KHOA( TENKHOA) values (
		N'Nội')
insert into KHOA( TENKHOA) values ( 
		N'Ngoai')
insert into KHOA( TENKHOA) values (
		N'Tai-Mũi-Họng')
insert into KHOA( TENKHOA) values (
		N'Nhi ')
insert into KHOA( TENKHOA) values (
		N'Sản')
insert into KHOA( TENKHOA) values (
		N'Da liễu')
insert into KHOA( TENKHOA) values (
		N'Tiêu hóa-Gan mật')
insert into KHOA( TENKHOA) values (
		N'Thần kinh')
insert into KHOA( TENKHOA) values (
		N'Nhãn khoa')
insert into KHOA( TENKHOA) values (
		N'Dinh dưỡng')
insert into KHOA( TENKHOA) values (
		N'Nội tiết')
insert into KHOA( TENKHOA) values (
		N'Hô hấp')
insert into KHOA( TENKHOA) values (
		N'Tim mạch')
insert into KHOA( TENKHOA) values (
		N'Nha khoa')


		insert into ACCOUNT(USERNAME ,TEN , CHUCVU ,MAKHOA,type ) values (
		N'admin',
		N'admin',
		N'admin',
		1,
		0
		)
		insert into ACCOUNT(USERNAME ,TEN , CHUCVU ,MAKHOA ,type ) values (
		N'bacsy',
		N'Cu Huy Duc',
		N'truong khoa',
		1,
		1
		)

		insert into ACCOUNT(USERNAME ,TEN , CHUCVU ,MAKHOA ,type ) values (
		N'yta',
		N'Hoang thi Linh',
		N'Truong y ta',
		3,
		2
		)
	

insert into BENHNHAN(HOTEN , GIOITINH, NGHENGHIEP, NGAYSINH, DIACHI, SDT ) values (
		N'Nguyen van A',
		N'Nam',
		N'Giao vien',
		'3/5/1990',
		N'quang trung',
		N'09083132113'
		)
insert into BENHNHAN(HOTEN , GIOITINH, NGHENGHIEP, NGAYSINH, DIACHI, SDT ) values (
		N'Nguyen Van B',
		N'Nu',
		N'Cong nhan',
		'3/5/2000',
		N'ngo quyen',
		N'0912321312'
		)

insert into BENHNHAN(HOTEN , GIOITINH, NGHENGHIEP, NGAYSINH, DIACHI, SDT ) values (
		N'Luong son bai',
		N'Nu',
		N'nhan vien',
		'3/5/1994',
		N'giai phong',
		N'090456746'
		)

insert into BENHNHAN(HOTEN , GIOITINH, NGHENGHIEP, NGAYSINH, DIACHI, SDT ) values (
		N'Le Nhat Vu',
		N'Nu',
		N'Doanh nghiep',
		'3/5/1980',
		N'nguyen tat thanh',
		N'0907457869'
		)

		GO
CREATE PROCEDURE GetListKhoa
AS
BEGIN
	Select * FROM KHOA 
END
GO


CREATE PROCEDURE GetListKhoaByIDAccount
@id int
AS
BEGIN
	Select * FROM KHOA where MAKHOA =@id
END
GO

-------------

--KETQUA

CREATE PROCEDURE GetListKetQuaByBenhNhanID
@id int
AS
BEGIN
	SELECT * FROM KETQUA  k inner join LANKHAM  l ON K.MALANKHAM=l.MALANKHAM AND l.MABENHNHAN = @id
END
GO

CREATE PROCEDURE GetListKetQua
AS
BEGIN
	SELECT * FROM KETQUA
END
GO

CREATE PROCEDURE GetListKetQuaByKetQua
@id int,
@KETQUA nvarchar(200)
AS
BEGIN
	SELECT * FROM KETQUA k , LANKHAM l
	WHERE k.KETQUA like '%'+@KETQUA+'%' and k.MALANKHAM = l.MALANKHAM and l.MABENHNHAN = @id;
END
GO

CREATE PROCEDURE GetListKetQuaByLanKham
@LanKhamID int
AS
BEGIN
	SELECT * FROM KETQUA WHERE MALANKHAM = @LanKhamID
END
GO

CREATE PROCEDURE AddKetQua
@MALANKHAM int ,
@KETQUA nvarchar(200)
AS
BEGIN
	INSERT INTO KETQUA(MALANKHAM, KETQUA)
	VALUES( @MALANKHAM, @KETQUA)
END
GO

CREATE PROCEDURE UpdateKetQua
@MAKETQUA int ,
@MALANKHAM int ,
@KETQUA varchar(200)
AS
BEGIN
UPDATE KETQUA
	SET  MALANKHAM = @MALANKHAM, KETQUA= @KETQUA
	WHERE MAKETQUA = @MAKETQUA
END
GO


CREATE PROCEDURE DeleteKetQua
@MAKETQUA int
AS
BEGIN
	DELETE KETQUA
	WHERE MAKETQUA= @MAKETQUA
END
GO

-------------------------

--Thuoc
CREATE PROCEDURE GetListThuoc
AS
BEGIN
	SELECT * from THUOC;
END
GO

CREATE PROCEDURE GetListThuocByTen
@TEN nvarchar(40)
AS
BEGIN
	SELECT * from THUOC WHERE TENTHUOC like  '%'+@TEN+'%'
END
GO

CREATE PROCEDURE AddThuoc
@TENTHUOC nvarchar(40),
@DONGIA money ,
@SOLUONG int 
AS
BEGIN
INSERT INTO	THUOC(TENTHUOC, DONGIA, SOLUONG)
VALUES(@TENTHUOC, @DONGIA, @SOLUONG);
END
GO


CREATE PROCEDURE UpdateThuoc
@MATHUOC int,
@TENTHUOC nvarchar(40),
@DONGIA money ,
@SOLUONG int 
AS
BEGIN
	UPDATE THUOC
	SET TENTHUOC=@TENTHUOC, DONGIA=@DONGIA, SOLUONG = @SOLUONG
	WHERE MATHUOC=@MATHUOC;
END
GO

CREATE PROCEDURE DeleteThuoc
@MATHUOC int
AS 
BEGIN
DELETE THUOC
WHERE MATHUOC = @MATHUOC;
END
GO
-----------

--CTTT
CREATE PROCEDURE ThongTinCTTT
@MACTT int
AS
BEGIN
	SELECT * FROM CTTT WHERE MACTTT=@MACTT;
END
GO

CREATE PROCEDURE AddCTTT
@MATOATHUOC int ,
@SOVIEN int ,
@MATHUOC int
AS
BEGIN
	INSERT INTO CTTT(MATOATHUOC, SOVIEN,MATHUOC)
	VALUES(@MATOATHUOC, @SOVIEN,@MATHUOC)
END
GO

CREATE PROCEDURE UpdateCTTT
@MACTTT int,
@MATOATHUOC int ,
@SOVIEN int ,
@MATHUOC int
AS
BEGIN
UPDATE CTTT
	SET MATOATHUOC = @MATOATHUOC, SOVIEN=@SOVIEN, MATHUOC=@MATHUOC
	WHERE MACTTT=@MACTTT;
END
GO

CREATE PROCEDURE DeleteCTTT
@MACTTT int
AS
BEGIN
	DELETE CTTT
	WHERE MACTTT=@MACTTT;
END
GO

CREATE PROCEDURE GetListCTTT
AS
BEGIN
	SELECT * FROM CTTT
END
GO

CREATE PROCEDURE GetListCTTTByMaToaThuocID
@MaToaThuocID int
AS
BEGIN
	SELECT c.MACTTT, c.MATOATHUOC, c.MATHUOC, t.TENTHUOC, c.SOVIEN FROM CTTT c, THUOC t
	WHERE c.MATOATHUOC = @MaToaThuocID and c.MATHUOC = t.MATHUOC
END
GO


CREATE PROCEDURE GetThongTinBenhNhan
@id int
AS
BEGIN
SELECT * FROM BENHNHAN WHERE MABENHNHAN = @id
END
GO
----------------

--BenhNhan

CREATE PROCEDURE GetListBenhNhan
AS
BEGIN
SELECT * FROM BENHNHAN;
END
GO

CREATE PROCEDURE UpdateBenhNhan
	@MABENHNHAN int,
	@HOTEN nvarchar(40),
	@GIOITINH nvarchar(4),
	@NGHENGHIEP nvarchar(40),
	@NGAYSINH datetime,
	@DIACHI nvarchar(40),
	@SDT nvarchar(12)
AS
BEGIN
UPDATE BENHNHAN
SET HOTEN=@HOTEN, GIOITINH=@GIOITINH, NGHENGHIEP=@NGHENGHIEP, NGAYSINH=@NGAYSINH, DIACHI=@DIACHI, SDT=@SDT
WHERE MABENHNHAN = @MABENHNHAN;
END
GO


CREATE PROCEDURE DeleteBenhNhan
@MABENHNHAN int
AS
BEGIN
DELETE BENHNHAN
WHERE MABENHNHAN = @MABENHNHAN;
END
GO

CREATE PROCEDURE AddBenhNhan
@HOTEN nvarchar(40),
@GIOITINH nvarchar(4),
@NGHENGHIEP nvarchar(40),
@NGAYSINH date,
@DIACHI nvarchar(40),
@SDT nvarchar(12)
AS
BEGIN
INSERT INTO BENHNHAN(HOTEN, GIOITINH, NGHENGHIEP, NGAYSINH, DIACHI, SDT)
VALUES(@HOTEN, @GIOITINH, @NGHENGHIEP, @NGAYSINH, @DIACHI, @SDT);
END
GO

--ACCOUNT

CREATE PROCEDURE UpdatePassword
	@UserName nvarchar(40),
	@Password nvarchar(40),
	@newPassword nvarchar(20)
	AS
	BEGIN
		DECLARE @isRightPass INT = 0
		SELECT @isRightPass = COUNT(*) FROM ACCOUNT WHERE UserName=@UserName AND MATKHAU=@Password
		IF(@isRightPass = 1)
		BEGIN
				BEGIN
				UPDATE ACCOUNT SET MATKHAU=@newPassword WHERE USERNAME=@UserName
				END
		END
	END
	GO


CREATE PROCEDURE ThongTinAccount
@UserName nvarchar(40)
AS
BEGIN
	Select USERNAME,TEN,CHUCVU,k.TENKHOA FROM ACCOUNT a left join KHOA k on a.MAKHOA=k.MAKHOA;
END
GO

CREATE PROCEDURE UserLogin
@UserName  nvarchar(40), 
@Password nvarchar(40)
AS
BEGIN
	SELECT * FROM ACCOUNT a where a.UserName = @UserName AND a.MatKhau= @Password
END
GO

CREATE PROCEDURE GetListAccount
AS
BEGIN
	Select USERNAME,TEN, CHUCVU, a.type, a.MAKHOA ,k.TENKHOA FROM ACCOUNT a left join KHOA k on a.MAKHOA=k.MAKHOA
END
GO

CREATE PROCEDURE GetListAccountByTen
@TEN nvarchar(40)
AS
BEGIN
	Select USERNAME,TEN, CHUCVU, a.type, a.MAKHOA ,k.TENKHOA FROM ACCOUNT a left join KHOA k on a.MAKHOA=k.MAKHOA 
	WHERE TEN like  '%'+@TEN+'%'
END
GO

CREATE PROCEDURE AddAccount
	@USERNAME nvarchar(40),
	@TEN nvarchar(40),
	@CHUCVU varchar(40),
	@MAKHOA int ,
	@type int 
AS
BEGIN
	if not exists(select top 1 USERNAME from ACCOUNT where USERNAME = @USERNAME)
	INSERT INTO ACCOUNT(USERNAME, TEN, CHUCVU, MAKHOA, type, MATKHAU)
	VALUES( @USERNAME, @TEN, @CHUCVU, @MAKHOA, @type, N'1');
END
GO


CREATE PROCEDURE UpdateAccount
@USERNAME nvarchar(40),
@TEN nvarchar(40) ,
@CHUCVU nvarchar(40),
@MAKHOA int, 
@type int 
AS
BEGIN
	UPDATE ACCOUNT
	SET  TEN=@TEN, CHUCVU=@CHUCVU, MAKHOA= @MAKHOA, type=@type
	WHERE USERNAME = @USERNAME;
END
GO

CREATE PROCEDURE DeleteAccount
@USERNAME nvarchar(40)
AS
BEGIN
	DELETE ACCOUNT
	WHERE USERNAME=@USERNAME;
END
GO

CREATE PROCEDURE ResetPassword
@USERNAME nvarchar(40)
AS
BEGIN
	UPDATE ACCOUNT
	SET MATKHAU = N'1'
	WHERE USERNAME = @USERNAME
END
GO

-----------------

--Phong
CREATE PROCEDURE GetListPhong
AS
BEGIN
	SELECT p.*, l.TENLOAIPHONG, l.DONGIA from PHONG p inner join LOAIPHONG l on p.MALOAIPHONG=l.MALOAIPHONG
END
GO

CREATE PROCEDURE GetListPhongByLoaiPhongID
@id int
AS
BEGIN
	SELECT p.*, l.TENLOAIPHONG, l.DONGIA from PHONG p inner join LOAIPHONG l on p.MALOAIPHONG=l.MALOAIPHONG 
	where p.MALOAIPHONG = @id
END
GO

CREATE PROCEDURE AddPhong
@SOGIUONG int,
@MALOAIPHONG  int
AS
BEGIN
	INSERT INTO PHONG(SOGIUONG,  MALOAIPHONG)
	VALUES (@SOGIUONG,  @MALOAIPHONG)
END
GO

CREATE PROCEDURE UpdatePhong
@MAPHONG int,
@SOGIUONG int,
@MALOAIPHONG int
AS
BEGIN
	UPDATE PHONG
		SET SOGIUONG=@SOGIUONG,  MALOAIPHONG=@MALOAIPHONG
		WHERE MAPHONG=@MAPHONG;

END
GO

CREATE PROCEDURE DeletePhong
@MAPHONG int
AS
BEGIN
	DELETE PHONG
	WHERE MAPHONG=@MAPHONG;
END
GO

------------------------------

--ToaThuoc

CREATE PROCEDURE GetListToaThuocByBenhNhanID
@id int
AS
BEGIN
	SELECT t.*
	FROM LANKHAM l, KETQUA k ,TOATHUOC t
	WHERE  k.MALANKHAM = l.MALANKHAM and k.MAKETQUA = t.MAKETQUA and l.MABENHNHAN = @id
END
GO

CREATE PROCEDURE GetListToaThuocByKetQuaID
@MAKETQUA int
AS
BEGIN
	SELECT * from TOATHUOC where MAKETQUA = @MAKETQUA
END
GO

CREATE PROCEDURE GetListToaThuoc
AS
BEGIN
	SELECT t.* ,b.MABENHNHAN , b.HOTEN, b.NGAYSINH
	FROM TOATHUOC t , KETQUA k, LANKHAM l, BENHNHAN b
	WHERE t.MAKETQUA = k.MAKETQUA and k.MALANKHAM = l.MALANKHAM and l.MABENHNHAN = b.MABENHNHAN
END
GO

CREATE PROCEDURE AddToaThuoc
@MAKETQUA int,
@SONGAY int
AS
BEGIN
INSERT INTO TOATHUOC(MAKETQUA, SONGAY)
VALUES(@MAKETQUA, @SONGAY);
END
GO

CREATE PROCEDURE UpdateToaThuoc
@MATOATHUOC int	,
@MAKETQUA int,
@SONGAY int
AS
BEGIN
	UPDATE TOATHUOC
	SET MAKETQUA=@MAKETQUA, SONGAY= @SONGAY
	WHERE MATOATHUOC=@MATOATHUOC;
END
GO

CREATE PROCEDURE DeleteToaThuoc
@MATOATHUOC int
AS
BEGIN
	DELETE TOATHUOC
	WHERE MATOATHUOC = @MATOATHUOC;
END
GO

----------------------------------------------------

--LichKham

CREATE PROCEDURE UpdateTinhTrangLanKham
@MALANKHAM int
AS
BEGIN
	UPDATE LANKHAM
	SET TINHTRANG = 'Đã khám'
	WHERE MALANKHAM = @MALANKHAM
END
GO

CREATE PROCEDURE DanhSachLanKhamBN
@MABENHNHAN int
AS
BEGIN
	Select * FROM LANKHAM WHERE MABENHNHAN=@MABENHNHAN;
END
GO


CREATE PROCEDURE GetListBenhNhanByTen
@TEN nvarchar(40)
AS
BEGIN
	
	SELECT * from BENHNHAN where HOTEN like  '%'+@TEN+'%'
END
GO

EXEC GetListLanKhamByKhoaAndNgay 1, '2018-6-14'

CREATE PROCEDURE GetListLanKhamByKhoaAndNgay
@Khoa int,
@Ngay date
AS
BEGIN
	SELECT l.MALANKHAM, l.MABENHNHAN , b.HOTEN, b.NGAYSINH
	FROM LANKHAM l, BENHNHAN b
	WHERE l.MABENHNHAN = b.MABENHNHAN and MAKHOA = @Khoa and NGAYKHAM = @Ngay  and TINHTRANG = N'Chưa khám'
END
GO

CREATE PROCEDURE GetListLanKhamByNgay
@NGAY date
AS
BEGIN
	SELECT * FROM LANKHAM WHERE NGAYKHAM >= @NGAY and NGAYKHAM <= getdate()
END
GO


CREATE PROCEDURE GetListLanKham
AS
BEGIN
	SELECT l.MALANKHAM, l.MABENHNHAN , b.HOTEN, b.NGAYSINH, l.MAKHOA, l.NGAYKHAM, l.TINHTRANG
	FROM LANKHAM l , BENHNHAN b
	WHERE l.MABENHNHAN = b.MABENHNHAN
END
GO

CREATE PROCEDURE GetListLanKhamByBenhNhanID
@MABENHNHAN int 
AS
BEGIN
	SELECt * FROM LANKHAM WHERE MABENHNHAN = @MABENHNHAN
END
GO

CREATE PROCEDURE AddLanKham
@MABENHNHAN  int ,
@MAKHOA int,
@NGAYKHAM date
AS
BEGIN
	INSERT INTO LANKHAM(MABENHNHAN ,MAKHOA, NGAYKHAM) 
	VALUES (@MABENHNHAN, @MAKHOA, @NGAYKHAM) 
END
GO


CREATE PROCEDURE UpdateLanKham
@MALANKHAM int ,
@MABENHNHAN  int ,
@MAKHOA int ,
@NGAYKHAM date,
@TINHTRANG nvarchar(20) 
AS
BEGIN
	UPDATE LANKHAM 
	SET MABENHNHAN =@MABENHNHAN, MAKHOA= @MAKHOA, NGAYKHAM = @NGAYKHAM,  TINHTRANG = @TINHTRANG
	WHERE MALANKHAM = @MALANKHAM
END
GO

CREATE PROCEDURE DeleteLanKham
@MALANKHAM int
AS
BEGIN
	DELETE LANKHAM
	WHERE MALANKHAM = @MALANKHAM
END
GO

---------------

--LoaiPhong
CREATE PROCEDURE GetListLoaiPhong
AS
BEGIN
	SELECT * FROM LOAIPHONG
END
GO


CREATE PROCEDURE GetListLoaiPhongByPhongID
@MALOAIPHONG int
AS
BEGIN
	SELECT * FROM LOAIPHONG WHERE MALOAIPHONG=@MALOAIPHONG
END
GO

-----------------

--NhapVien

CREATE PROCEDURE UpdateTinhTrangNhapVien
@id int 
AS
BEGIN
	UPDATE NHAPVIEN 
	SET TINHTRANG = 'Đã nhập'
	WHERE MANHAPVIEN = @id
END
GO

CREATE PROCEDURE GetListNhapVienByBenhNhanID
@id int
AS
BEGIN
	SELECT n.*
	FROM NHAPVIEN n, KETQUA k, LANKHAM l
	WHERE l.MABENHNHAN = @id and l.MALANKHAM = k.MALANKHAM and k.MAKETQUA= n.MAKETQUA
	
END
GO
CREATE PROCEDURE GetListNhapVien
AS
BEGIN
	SELECT n.MANHAPVIEN, n.NGAYNHAP, n.NGAYXUAT, b.MABENHNHAN, b.HOTEN, b.NGAYSINH, n.TINHTRANG
	FROM NHAPVIEN n, KETQUA k, LANKHAM l, BENHNHAN b
	WHERE n.MAKETQUA = k.MAKETQUA and k.MALANKHAM = l .MALANKHAM and l.MABENHNHAN = b.MABENHNHAN and n.TINHTRANG like 'Chưa nhập'
END
GO



CREATE PROCEDURE GetListNhapVienByTen
@TEN nvarchar(40)
AS
BEGIN
	SELECT n.*, b.HOTEN
	FROM NHAPVIEN n, KETQUA k, LANKHAM l, BENHNHAN b
	WHERE n.MAKETQUA = k.MAKETQUA and k.MALANKHAM = l .MALANKHAM and l.MABENHNHAN = b.MABENHNHAN and b.HOTEN like  '%'+@TEN+'%' and l.TINHTRANG like 'Chưa khám';
END
GO

CREATE PROCEDURE GetListNhapVienByKetQua
@MAKETQUA int
AS
BEGIN
	SELECT * FROM NHAPVIEN WHERE MAKETQUA = @MAKETQUA
END
GO

CREATE PROCEDURE AddNhapVien
@MAKETQUA int ,
@NGAYNHAP date ,
@NGAYXUAT date
AS
BEGIN
	INSERT INTO NHAPVIEN(MAKETQUA, NGAYNHAP, NGAYXUAT)
	VALUES (@MAKETQUA, @NGAYNHAP, @NGAYXUAT)
END
GO

CREATE PROCEDURE UpdateNhapVien
@MANHAPVIEN int ,
@MAKETQUA int ,
@NGAYNHAP date ,
@NGAYXUAT date
AS
BEGIN
	UPDATE NHAPVIEN
	SET  MAKETQUA= @MAKETQUA, NGAYNHAP = @NGAYNHAP, NGAYXUAT = @NGAYXUAT
	WHERE MANHAPVIEN = @MANHAPVIEN
END
GO
CREATE PROCEDURE DeleteNhapVien
@MANHAPVIEN int
AS
BEGIN
	DELETE NHAPVIEN
	WHERE MANHAPVIEN = @MANHAPVIEN
END
GO


CREATE PROCEDURE GetListChiTietNhapVien
AS
BEGIN
	SELECT c.* , b.MABENHNHAN, b.HOTEN, b.NGAYSINH 
	FROM CHITIETNHAPVIEN c, NHAPVIEN n , KETQUA k , LANKHAM l ,BENHNHAN b
	WHERE c.MANHAPVIEN = n.MANHAPVIEN and n.MAKETQUA = k.MAKETQUA and k.MALANKHAM = l.MALANKHAM and l.MABENHNHAN = b.MABENHNHAN
END
GO


-------------------------

CREATE PROCEDURE GetListCTNVByTenBenhNhan
@TEN nvarchar(40)
AS
BEGIN
	SELECT c.MACHITIETNHAPVIEN , c.MANHAPVIEN, c.MAPHONG , b.MABENHNHAN, b.HOTEN, b.NGAYSINH
	FROM CHITIETNHAPVIEN c, NHAPVIEN n, KETQUA k , LANKHAM l , BENHNHAN b
	WHERE c.MANHAPVIEN = n.MANHAPVIEN and n.MAKETQUA = k.MAKETQUA and k.MALANKHAM = l.MALANKHAM 
	and l.MABENHNHAN = b.MABENHNHAN and b.HOTEN like '%'+@TEN+'%'
END
GO





CREATE PROCEDURE AddChiTietNhapVien
@MANHAPVIEN int ,
@MAPHONG int  
AS
BEGIN
	INSERT INTO CHITIETNHAPVIEN(MANHAPVIEN, MAPHONG)
	VALUES(@MANHAPVIEN, @MAPHONG)
	UPDATE PHONG  SET SOBENHNHAN =SOBENHNHAN +1 WHERE MAPHONG = @MAPHONG
END
GO

CREATE PROCEDURE UpdateChiTietNhapVien
@MACHITIETNHAPVIEN int,
@MANHAPVIEN int,
@MAPHONG int  
AS
BEGIN
UPDATE CHITIETNHAPVIEN
	SET MANHAPVIEN = @MANHAPVIEN, MAPHONG =@MAPHONG
	WHERE MACHITIETNHAPVIEN =@MACHITIETNHAPVIEN
END
GO


CREATE PROCEDURE DeleteChiTietNhapVien
@MACHITIETNHAPVIEN int
AS
BEGIN
	DELETE CHITIETNHAPVIEN
	WHERE MACHITIETNHAPVIEN =@MACHITIETNHAPVIEN
END
GO

